# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40ab967da712cd165d9823e0f34d7c9fa0c9a2060e3297ed12b47039a0ec8a2c209c40ae4a437914bad334e5570f1f08d7259c30762a2f4b4df78fce2357d216

test:
  secret_key_base: 269be2c889ae491b6df37ac0e8cda390f3139bbbc8dc3dddf6c71cb264fb579000ad63b9d2023eafb45bf1d3fefc22a06c2ffe064728724c07327a4988111cfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
